spring:
  data:
    mongodb:
      uri: mongodb+srv://cyrillezhou:ultrabookshelf@ultrabookshelf.odcbf.mongodb.net/bookShelf?retryWrites=true&w=majority

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  address: 0.0.0.0
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
