spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/database

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

server:
  port: 8080
